workspace("openswf")
    configurations({ "debug", "release" })
    location("build")

    filter("configurations:debug")
        defines({"DEBUG"})
        flags({"Symbols"})

    filter("configurations:release")
        defines({"NDEBUG"})
        optimize("On")

    project("tess2")
        language("C")
        kind("StaticLib")
        includedirs({ "3rd/libtess2/Include", "3rd/libtess2/Source" })
        files({ "3rd/libtess2/Source/*.c" })
        targetdir("libs")

    project("unit-test")
        kind("ConsoleApp")
        language("C++")
        buildoptions({"-std=c++11", "-stdlib=libc++"})
        location("build/unit-test")
        libdirs({"libs"})
        links({"tess2"})
        files({"test/unit-test/**.cpp", "source/**.cpp"})
        includedirs({ "3rd/catch/include", "3rd/libtess2/Include", "source" })
